name: Deploy to AWS ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "ap-south-1"   # ✅ FIXED (quotes added)

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: docker build -t myapp:latest ./app

      - name: Tag Docker image
        run: docker tag myapp:latest ${{ steps.login-ecr.outputs.registry }}/myapp:latest

      - name: Push to ECR
        run: docker push ${{ steps.login-ecr.outputs.registry }}/myapp:latest
