name: Deploy to AWS ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Amazon ECR
      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: ${{ ap-south-1 }}

      # Step 3: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t myapp:latest ./app

      # Step 4: Tag Docker image for ECR
      - name: Tag Docker image
        run: |
          docker tag myapp:latest ${{ 756546933552 }}.dkr.ecr.${{ ap-south-1 }}.amazonaws.com/myapp:latest

      # Step 5: Push Docker image to ECR
      - name: Push Docker image
        run: |
          docker push ${{ 756546933552 }}.dkr.ecr.${{ ap-south-1 }}.amazonaws.com/myapp:latest

      # Step 6: Deploy to ECS (optional, if you have ECS service ready)
      - name: Update ECS service
        run: |
          aws ecs update-service --cluster my-cluster --service my-service --force-new-deployment --region ${{ ap-south-1 }}
